config/routes.rb
Rails.application.routes.draw do

  get 'search/class_find'
  get 'search/student_find'
  get 'search/index_student'
  get 'search/index'

  resources :users
  resources :students
  resources :teachers
  resources :homes
  # devise_for :admins
  devise_for :user



  root :to => 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :home
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :appointments
  validates :name, presence: true, uniqueness: {message:"班级名称已存在"}
  belongs_to :user
  has_many :students  #dependent: :destroy
  has_many :users, through: :appointments  #dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: {:message => "姓名不能为空"}
  belongs_to :home
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :homes, through: :appointments #dependent: :destroy,
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, except: [:index, :new, :create]
  before_action :authenticate_user!, :only => [:index, :new]

  def index
    # if会自动判断是否为nil
    #if params[:inquire] == nil
    if params[:inquire]
      @homes = User.find(params[:inquire]).homes
      @homes = @homes.paginate(:page => params[:page], :per_page => 3)
    else
      @homes = Home.paginate(:page => params[:page], :per_page => 3)
    end
  end

  def show
    #current_user 就是一个实例
    # @homes = User.find(current_user.id).homes
    @homes = current_user.homes
  end

  def new
    @home = Home.new
  end


  def edit

  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)
    respond_to do |format|
      if @home.save
        @appointment = Appointment.new
        @appointment.home_id = @home.id
        @appointment.user_id = current_user.id
        @appointment.save
        format.html { redirect_to @home, notice: '班级创建成功' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        @home.users << User.find_by_id(@home.append)
        format.html { redirect_to @home, notice: '班级更新成功' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: '班级删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_home
    @home = Home.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def home_params
    params.require(:home).permit(:name, :append)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def class_find
  end

  def student_find
  end

  def index
    #通过传入的参数，查找到home的实例，如果不存在，会出错（实例不存在）
    @home = Home.find_by_name(params[:s])
  end

  def index_student
    #通过传入的参数，查找到home的实例，如果不存在，返回的是一个[]（空数组），可以通过他的@students.length != 0来判断
    @students = Student.where(:name => params[:s])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, except: [:index, :new, :create]


  # GET /students
  # GET /students.json
  def index
    # byebug
    if params[:query]
      @students = Home.find(params[:query]).students
      @students = @students.paginate(:page => params[:page], :per_page => 3)
    else
      @students = Student.paginate(:page => params[:page], :per_page => 3)
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show

  end

  # GET /students/new
  def new
    @student = Student.new
    @student.home_id = params[:home_id]
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: '学生创建成功' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update

    respond_to do |format|
      if @student.update(student_params)

        format.html { redirect_to @student, notice: '学生更新成功' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      # redirect_to students_url 这个是删除以后刷新当前界面，因为学生index中的参数是从班级名称点击过来的（携带参数），
      # 所以这样写会出错，应该写成 back 这样就重新走index这个方法
      format.html { redirect_to :back, notice: '学生删除成功' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:name, :home_id)

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users =User.paginate(:page => params[:page], :per_page => 3)
    # @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :home_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>

    <% if home.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

          <ul>
            <% home.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_area :name %>
    </div>

    <div class="field">
      <%= f.label :score %>
      <%= f.text_field :score %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/homes/edit.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= form_for @home, :html => {:class => "form-horizontal home"} do |f| %>

    <% if @home.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@hone.errors.count, "error") %> prohibited this home from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @home.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <h3>已有老师列表</h3>

    <table>
      <thead>
      <tr>
        <th>老师编号|</th>
        <th>老师邮箱|</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <!--<tbody>-->
      <!--<%# User.all.each do |user| %>-->
          <!--<tr>-->
            <!--<td><#%= user.id %></td>-->
            <!--<td><#%= user.email %></td>-->
          <!--</tr>-->
      <!--<%# end %>-->
      <!--</tbody>-->
    </table>

    <h4><%= "须移动班级：#{@home.name} (#{@home.id})" %></h4>

    <table>
      <thead>
      <tr>
        <th>老师编号|</th>
        <th>老师邮箱|</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @home.users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <div class="form-group">
      <%= f.label :添加老师编号, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%#= f.text_field :append, :class => 'form-control' %>
        <%= f.collection_select(:append, User.all, :id, :email) %>
      </div>
      <%= f.error_span(:append) %>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.返回")),
                    homes_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>
<h3>
  <% if current_user.id == 1 %>
      <% a = "管理员" %>
  <% else %>
      <% a = "老师" %>
  <% end %>
  <%= "当前用户：#{current_user.email} (#{a})" %>
</h3>

<br>


<div class="well">
  <h1>班级列表</h1>
  <table>
    <thead>
    <tr>
      <th>班级编号|</th>
      <th>班级名称|</th>
      <th>班级评分|</th>
      <th>班级口号|</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @homes.each do |home| %>
        <tr>
          <td><%= link_to home.id, home_path(home) %></td>
          <td><%= link_to home.name, students_path(query: "#{home.id}") %></td>
          <td><%= home.score %></td>
          <td><%= home.description %></td>
          <td><%= link_to (t 'show'), home %></td>
          <td>
            <% if current_user.id == 1 %>
                <%= link_to (t 'edit'), edit_home_path(home) %>
            <% end %>
          </td>
          <td>
            <% if current_user.id == 1 %>
                <%= link_to (t 'destroy'), home, method: :delete, data: {confirm: '确定删除？'} %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @homes, renderer: BootstrapPagination::Rails %>
</div>



<%= link_to t('new_memo'), new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to '返回', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %>
</p>

<p>
  <strong>姓名:</strong>
  <%= @home.name %>

</p>

<p>
  <strong>分数:</strong>
  <%= @home.score %>
</p>

<p>
  <strong>评分:</strong>
  <%= @home.description %>
</p>

<% if current_user.id == 1 %>
    <%= link_to (t 'edit'), edit_home_path(@home) %>
<% end %>


<%= link_to '返回', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "学生管理系统" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">学生管理</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li>
          <% if user_signed_in? && current_user.id ==1 %>
              <%= link_to "老师列表", users_path %>
          <% end %>
        </li>
        <li><%= link_to "班级列表", homes_path %></li>
        <li><%= link_to "学生列表", students_path  %></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <!--<h3>Sidebar</h3>-->
        <ul class="nav nav-list">
          <li class="nav-header"><%= Time.now.strftime('%Y年-%m月-%d日') %></li>
          <li>
            <% if user_signed_in? %><%= link_to "回到首页", homes_path %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %><%= link_to "班级搜索", search_class_find_path %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %><%= link_to "学生搜索", search_student_find_path %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %>
                <%= link_to "退出登录", destroy_user_session_path, method: :delete %>
            <% end %>
          </li>

        </ul>
      </div><!--/.well -->
    </div><!--/span-->
  </div><!--/row-->

  <footer>
    <p><%= Time.now.strftime('%Y年-%m月-%d日 %H时:%M分:%S秒') %></p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/search/class_find.html.erb
<html>

<head>
  <title>|搜索框</title>
  <meta charset="UTF-8">
  <style type="text/css">
  </style>
</head>
<body>
<div>
  <h2>搜索框</h2>
  <form method="get" id="searchform" action="/search/index">
    <fieldset class="search">
      <input type="text" class="box" name="s" id="s" class="inputText" placeholder="班级搜索" x-webkit-speech>
      <input title="SEARCH" type="submit"/>
    </fieldset>
  </form>
</div>
<article class="article">
</article>
</body>
</html>

app/views/search/index.html.erb
<h1>搜索结果</h1>

<p id="notice"><%= notice %>
</p>
<% if @home %>
    <p>
      <strong>姓名:</strong>
      <%= @home.name %>

    </p>

    <p>
      <strong>分数:</strong>
      <%= @home.score %>
    </p>

    <p>
      <strong>评分:</strong>
      <%= @home.description %>
    </p>
<%#if current_user.id == 1%>
    <%#= link_to (t 'edit'), edit_home_path(@home) %>
<%# end %>
    <!--x写法同上-->
    <%= link_to_if current_user.id == 1, "编辑", edit_home_path(@home) do %>
    <% end %>
    <td>
      <% if current_user.id == 1 %>
          <%= link_to (t 'destroy'), @home, method: :delete, data: {confirm: '确定删除？'} %>
      <% end %>
    </td>

<% else %>
    <h3> 🔍找不到搜索的班级 </h3>
<% end %>

<%= link_to '返回', search_class_find_path %>

app/views/search/index_student.html.erb
<% if @students.length != 0 %>
    <%- model_class = Student -%>
    <div class="page-header">
      <h1>学生列表</h1>
    </div>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th>姓名</th>
        <th><%= model_class.human_attribute_name(:年龄) %></th>
        <th><%= model_class.human_attribute_name(:分数) %></th>
        <th><%= model_class.human_attribute_name(:创建时间) %></th>
        <th><%= t '.actions', :default => t("helpers.操作") %></th>
      </tr>
      </thead>
      <tbody>
      <% @students.each do |student| %>
          <tr>
            <td><%= link_to student.id, student_path(student) %></td>
            <td><%= student.name %></td>
            <td><%= student.age %></td>
            <td><%= student.score %></td>
            <td><%= l student.created_at %></td>
            <td>
              <% if current_user.id == 1 %>
                  <%= link_to t('.show', :default => t("helpers.links.展示")),
                              student_path(student), :class => 'btn btn-default btn-xs' %>
              <% end %>
              <% if current_user.id == 1 %>
                  <%= link_to t('.edit', :default => t("helpers.links.编辑")),
                              edit_student_path(student), :class => 'btn btn-default btn-xs' %>
              <% end %>
              <% if current_user.id == 1 %>
                  <%= link_to t('.destroy', :default => t("helpers.links.删除")),
                              student_path(student),
                              :method => :delete,
                              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '确定删除?'))},
                              :class => 'btn btn-xs btn-danger' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <h3> 🔍找不到搜索的学生 </h3>
<% end %>

<%= link_to t('返回', :default => t("helpers.links.返回")), search_student_find_path,
            :class => 'btn btn-primary' %>

app/views/search/student_find.html.erb
<html>

<head>
  <title>|搜索框的实现</title>
  <meta charset="UTF-8">
  <style type="text/css">
  </style>
</head>
<body>
<div>
  <h2>搜索框</h2>
  <form method="get" id="searchform" action="/search/index_student">
    <fieldset class="search">
      <input type="text" class="box" name="s" id="s" class="inputText" placeholder="学生搜索" x-webkit-speech>
      <input title="SEARCH" type="submit"/>
    </fieldset>
  </form>
</div>
<article class="article">
</article>
</body>
</html>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @student, :html => {:class => "form-horizontal student"} do |f| %>

    <% if @student.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @student.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <h3>可移动的班级列表</h3>

    <table>
      <thead>
      <tr>
        <th>班级编号|</th>
        <th>班级名称|</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <!--<tbody>-->
      <!--<%# Home.all.each do |home| %>-->
          <!--<tr>-->
            <!--<td><%#= link_to home.id, home_path(home) %></td>-->
            <!--<td><%#= link_to home.name, students_path(query: "#{home.id}") %></td>-->
          <!--</tr>-->
      <!--<%# end %>-->
      <!--</tbody>-->
    </table>

    <div class="form-group">
      <%= f.label :姓名, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%= f.error_span(:name) %>
    </div>

    <div class="form-group">
      <%= f.label :年龄, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :age, :class => 'form-control' %>
      </div>
      <%= f.error_span(:age) %>
    </div>

    <div class="form-group">
      <%= f.label :分数, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :score, :class => 'form-control' %>
      </div>
      <%= f.error_span(:score) %>
    </div>

    <div class="form-group">
      <%= f.label :移动至班级编号, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%#= f.text_field :home_id, value: @student.home_id %>
        <%= f.collection_select(:home_id, Home.all, :id, :name) %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.返回")),
                    homes_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/students/index.html.erb
<%- model_class = Student -%>

<h3>
  <% if current_user.id == 1 %>
      <% a = "管理员" %>
  <% else %>
      <% a = "老师" %>
  <% end %>
  <%= "当前用户：#{current_user.email} (#{a})" %>
</h3>
<div class="well">
  <div class="page-header">
    <h1>学生列表</h1>
  </div>

  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>姓名</th>
      <th><%= model_class.human_attribute_name(:年龄) %></th>
      <th><%= model_class.human_attribute_name(:分数) %></th>
      <th><%= model_class.human_attribute_name(:创建时间) %></th>
      <th><%= t '.actions', :default => t("helpers.操作") %></th>
    </tr>
    </thead>

    <tbody>
    <% @students.each do |student| %>
        <tr>
          <td><%= link_to student.id, student_path(student) %></td>
          <td><%= student.name %></td>
          <td><%= student.age %></td>
          <td><%= student.score %></td>
          <td><%= l student.created_at %></td>
          <td>
            <% if current_user.id == 1 %>
                <%= link_to t('.show', :default => t("helpers.links.展示")),
                            student_path(student), :class => 'btn btn-default btn-xs' %>
            <% end %>

            <% if current_user.id == 1 %>
                <%= link_to t('.edit', :default => t("helpers.links.编辑")),
                            edit_student_path(student), :class => 'btn btn-default btn-xs' %>
            <% end %>

            <%= link_to t('.destroy', :default => t("helpers.links.删除")),
                        student_path(student),
                        :method => :delete,
                        :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '确定删除?'))},
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= will_paginate @students, renderer: BootstrapPagination::Rails %>
</div>


<%= link_to t('新建', :default => t("helpers.links.新建")),
            new_student_path(home_id: params[:query]),
            :class => 'btn btn-primary' %>

<%= link_to t('返回', :default => t("helpers.links.返回")), homes_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>

<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<h3>
  <% if current_user.id == 1 %>
      <% a = "管理员" %>
  <% else %>
      <% a = "用户" %>
  <% end %>
  <%= "当前用户：#{current_user.email} (#{a})" %>
</h3>


<div class="well">
  <div class="page-header">
    <h1>老师列表</h1>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.操作") %></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to user.email, homes_path(inquire: "#{user.id}") %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.展示")),
                        user_path(user), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.编辑")),
                        edit_user_path(user), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.删除")),
                        user_path(user),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>


  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>